# GitHub Actions 缓存配置
# 用于自建 runner 的本地缓存设置

cache:
  # 默认缓存目录
  base_dir: "/tmp/action"

  # 缓存保留策略
  retention:
    # 保留天数
    days: 7
    # 最大缓存文件数
    max_files: 50
    # 最大缓存大小 (GB)
    max_size_gb: 10

  # Go 相关缓存配置
  go:
    # Go 模块缓存
    modules:
      path: "/tmp/action/go-modules"
      retention_days: 30

    # Go 构建缓存
    build:
      path: "/tmp/action/go-build"
      retention_days: 7

    # golangci-lint 缓存
    lint:
      path: "/tmp/action/golangci-lint"
      retention_days: 14

  # 清理策略
  cleanup:
    # 是否启用自动清理
    enabled: true
    # 清理间隔（小时）
    interval_hours: 24
    # 并行清理任务数
    parallel_jobs: 2

# 自建 runner 检测配置
runner_detection:
  # 检测方法优先级
  methods:
    - runner_name_pattern  # 检查 RUNNER_NAME 是否包含特定模式
    - environment_variable # 检查环境变量
    - marker_file         # 检查标识文件

  # Runner 名称模式
  name_patterns:
    - "lazy"
    - "self-hosted"
    - "local"

  # 环境变量检查
  env_vars:
    - "RUNNER_ENVIRONMENT=self-hosted"
    - "CI_RUNNER_TYPE=self-hosted"

  # 标识文件路径
  marker_files:
    - "/etc/github-runner/self-hosted"
    - "/opt/actions-runner/.self-hosted"
    - "~/.github-runner-self-hosted"

# 监控和日志
monitoring:
  # 是否启用缓存使用统计
  enable_stats: true

  # 统计文件路径
  stats_file: "/tmp/action/stats.json"

  # 日志级别
  log_level: "info"